name: Python package
on: [push]
#defaults:
#  run:
#    working-directory: wrdir
jobs:
  #deploy:
  #  runs-on: windows-latest
  #  steps:
  #    - name: install readline
  #      run: python -m pip install readline
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest] #,windows-latest
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: mkdir wrdir
        run: mkdir -p wrdir && mkdir -p wrdir/hiphp
      - name: copy files
        run: cp -r hiphp/* wrdir/hiphp && cp -r examples/* wrdir
      - name: pip Upgrade
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Testing the Package
        run: python wrdir/examples.py